### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by aoligei178** [CuiRuikai/Partial2Complete#17]
Hello! Thank you for your awesome work! I want to know about your training and inference speed. How long does it take to train your network? How many GPUs you have used?

**Comment by kefusong** [comment]
Hey, I am also concerned about them. Could the author offer more information about them?

**Comment by CuiRuikai** [comment]
I do not have exact training cost now, but, roughly, I set the batch size as 32 and use only a single RTX3090 GPU to train all models. (I found that setting the batch size as a very large number may have negative impact on performance.)
The inference speed is provided in the supplementary material. [supp](https://openaccess.thecvf.com/content/ICCV2023/supplemental/Cui_P2C_Self-Supervised_Point_ICCV_2023_supplemental.pdf)
