### ISSUE TITLE
How many numbers partial part for one sample during training？

### ISSUE THREAD

**Issue by xingjinderhuoche** [CuiRuikai/Partial2Complete#24]
Thanks for such good work, may I ask you to extract several partial parts for each sample in the experimental data set for sub-supervised training during training？

**Comment by CuiRuikai** [comment]
in the 3D-EPN dataset, it is 2048 points for both partial and complete
in the PCN and ScanNet datasets, the number of points in the partial point clouds various, but usually no more than 1k points

**Comment by xingjinderhuoche** [comment]
Thank you very much! In fact, I want to ask for a sample, such as the aircraft class in shapenet, for one of the aircraft in this class, there is a complete and multiple partial. In the paper, partial is used to restore the shape, so for an aircraft, how many partial is needed? Or to put it another way, how many partial units are usually used in self-supervised training? Is it one or more？
感谢！其实我想问对于某一个样本来说，比如说shapenet里面的飞机类，对于该类中的其中一个飞机，有一个complete，和多个partial，在论文里是用partial来恢复形状的，那么对于一个飞机来说，需要用到几个partial呀。或者换个问法，自监督训练中用到的partial一般是多少个呀，是一个还是多个呀。

**Comment by CuiRuikai** [comment]
just single partial shape

**Comment by xingjinderhuoche** [comment]
Thanks a lot！
