### ISSUE TITLE
About  visualization

### ISSUE THREAD

**Issue by xingjinderhuoche** [CuiRuikai/Partial2Complete#28]
Thanks for such good work, could you please share the visualization code of fig7 in the paper. Thanks a lot.

**Comment by CuiRuikai** [comment]
Sorry that I am not able to find the code for visualization. However, the method is very simple. Basically, I calculated the per-point loss, and normalized the value to [0,1]. Then, I generate a heatmap with the normalized value and get a RGB color for each point. Then, I use Open3D to draw the figure.

**Comment by CuiRuikai** [comment]
I have uploaded the visualization code in `misc/rcd_vis.ipynb`. However, I have not tested its compatibility on other devices. After generating the point cloud, I saved the output as PLY files and used MeshLab for visualization. The camera configuration for Figure 7 is provided at the bottom of the .ipynb file.

**Comment by xingjinderhuoche** [comment]
Thaks a lot!
