### ISSUE TITLE
Train on PCN_dataset and 3D-EPN

### ISSUE THREAD

**Issue by junkangma** [CuiRuikai/Partial2Complete#4]
Thank you for your work!
I want to konw when you train on PCN_dataset ,you train a single category and test it or  you train eight categories and test them.
Looking forward to your reply!

**Comment by CuiRuikai** [comment]
As we explained in the paper, we train on category-specific network on the PCN dataset. That is, we train and test on each category. Furthermore, the PCN models are trained with both partial and complete shapes (similar to unpaired setting) due to the fact that PCN objects have more occlusions than 3D-EPN.

**Comment by junkangma** [comment]
And I would like to know if it is also a single category training and testing on the 3D-EPN dataset.
Looking forward to your reply!

**Comment by CuiRuikai** [comment]
As far as I know, they are category-specific as well.
For cycle4completion, line 32 of https://github.com/diviswen/Cycle4Completion/blob/main/main_code.py indicated the category.
`parser.add_argument('--data_category', default='car', help='plane/car/lamp/chair/table/cabinet/watercraft/sofa')`
For Shape Inversion, if you download their pre-trained weight, there are eight models corresponding to the 8 categories. The link is here https://drive.google.com/drive/folders/1FA29POuh5hlg50ulCxSMjCImbgI6wxvR

**Comment by junkangma** [comment]
Have you tried to replicate the article CVPR2023ACL_SPC? I found that the code provided in the article used test_dataset during training and not tested on additional datasets. I modified it to train on the train_dataset and test on the test_dataset, but it seems that I did not get the results in the paper.Do you have the same confusion?

**Comment by junkangma** [comment]
Sorry, the above issue is in the real dataset experiment section

**Comment by CuiRuikai** [comment]
> Have you tried to replicate the article CVPR2023ACL_SPC? I found that the code provided in the article used test_dataset during training and not tested on additional datasets. I modified it to train on the train_dataset and test on the test_dataset, but it seems that I did not get the results in the paper.Do you have the same confusion?

Different from our work, they explained in their abstract that their method is trained and tested on the same data to satisfy the proposed adaptive closed-loop (ACL) system. Therefore, it is reasonable that testing on different samples leads to a worse result. However, at the time of we submit our paper to ICCV 2023, we haven't noticed this paper, so we did not test and compare this method.

**Comment by junkangma** [comment]
Okay, I understand what you mean. Thank you for your reply
