### ISSUE TITLE
distribution of prediction points

### ISSUE THREAD

**Issue by junkangma** [CuiRuikai/Partial2Complete#8]
Thank you for your work!
May I ask if there was any uneven distribution of prediction points during your testing on the PCN dataset? 
Looking forward to your reply!

**Comment by junkangma** [comment]
Another question I would like to ask you is, for all datasets（PCN、EPN3D、scannet...）, does the network output 2048 data points?
Looking forward to your reply!

**Comment by CuiRuikai** [comment]
> Thank you for your work! May I ask if there was any uneven distribution of prediction points during your testing on the PCN dataset? Looking forward to your reply!

Thank you for your interesting question. The point distribution focus mostly on observed regions, for unobserved regions. The points are very sparse. This is something we should improve.

**Comment by CuiRuikai** [comment]
> Another question I would like to ask you is, for all datasets（PCN、EPN3D、scannet...）, does the network output 2048 data points? Looking forward to your reply!

Yes, for all dataset, we set the number of output points as 2048
